### ISSUE TITLE
img2img not works any more

### ISSUE THREAD

**Issue by AngelTs** [camenduru/latent-consistency-model-colab#2]
/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py:750: FutureWarning: `torch_dtype` is deprecated and will be removed in version 0.25.0. 
  deprecate("torch_dtype", "0.25.0", "")
/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py:753: FutureWarning: `torch_device` is deprecated and will be removed in version 0.25.0. 
  deprecate("torch_device", "0.25.0", "")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/content/webui-lcm/scripts/main.py", line 158, in generate_i2i
    result = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/webui-lcm/lcm/lcm_i2i_pipeline.py", line 305, in __call__
    self.scheduler.set_timesteps(strength, num_inference_steps, original_inference_steps)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_lcm.py", line 377, in set_timesteps
    timesteps = lcm_origin_timesteps[::-skipping_step][:num_inference_steps]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by tralala87** [comment]
I get the same error.

**Comment by AngelTs** [comment]
> I get the same error.

It is works fine just before 3-5 days (last week, tested by me), but now it is not ...

**Comment by AngelTs** [comment]
The same error occures and in [sd-webui-lcm](https://github.com/0xbitches/sd-webui-lcm/issues/30):

File "C:\AUTOMATIC1111\venv\lib\site-packages\diffusers\schedulers\scheduling_lcm.py", line 382, in set_timesteps
timesteps = lcm_origin_timesteps[::-skipping_step][:num_inference_steps]

TypeError: slice indices must be integers or None or have an __index__ method

**Comment by rogalag** [comment]
The same error....

**Comment by camenduru** [comment]
thanks for the info ❤ please try again
